### ISSUE TITLE
Problems converting small images

### ISSUE THREAD

**Issue by javl** [javl/image2cpp#1]
Small and large images are handled the same way, but it seems small ones don't get converted properly. When I export a 10x10px image and use the output as input again, I do get the image I started with, but they don't appear right on the display. The error starts around images of around 14x14px.

Need to figure out if this is a problem with the export, or with the Adafruit display library.

**Comment by mobehun** [comment]
I have the same problem too. It happens for me with every picture I've tried. Most of them are 26x26 and are bigger.

**Comment by javl** [comment]
It has been a while since I used the tool and don't have a display set up to debug it at the moment, sorry. 
I'll look into it at some later time, but feel free to create a pull request if you manage to find the cause ;)

**Comment by javl** [comment]
I might have some idea of what's going on. I'll take another look but I'm not sure when I'll have the time.

**Comment by javl** [comment]
@mobehun Can you attach the image you're trying to convert, and the conversion result so I can test it later?

(To get the converted result, copy the generated code and use it as input at the top to generate an image from the code. You can then right click that image to save it.)

**Comment by mobehun** [comment]
![cloud](https://cloud.githubusercontent.com/assets/8471727/25483157/f48dc374-2b54-11e7-9836-b8c2758954b0.png)

I've tried this one as a BMP
`// 'Cloud'
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x3f, 0xf0, 0x00, 
0x00, 0x00, 0x03, 0xff, 0xf8, 0x00, 0x00, 0x00, 0x0f, 0xff, 0xfc, 0x00, 0x00, 0x00, 0x3f, 0xff, 
0xfc, 0x00, 0x00, 0x01, 0xfe, 0x01, 0xfc, 0x00, 0x00, 0x03, 0xf0, 0x00, 0xfc, 0x00, 0x00, 0x0f, 
0x80, 0x00, 0x7c, 0x00, 0x00, 0x3e, 0x00, 0x00, 0x7c, 0x00, 0x00, 0x78, 0x00, 0x00, 0x7f, 0xe0, 
0x01, 0xf0, 0x00, 0x00, 0xff, 0xf0, 0x03, 0xc0, 0x00, 0x00, 0xff, 0xf8, 0x07, 0x80, 0x00, 0x01, 
0xff, 0xf8, 0x1e, 0x00, 0x00, 0x00, 0x01, 0xf8, 0x3c, 0x00, 0x00, 0x00, 0x01, 0xf0, 0x78, 0x00, 
0x00, 0x00, 0x01, 0xf0, 0xf0, 0x00, 0x00, 0x00, 0x01, 0xe1, 0xe0, 0x00, 0x00, 0x00, 0x03, 0xc3, 
0xc0, 0x00, 0x00, 0x00, 0x03, 0xc7, 0x80, 0x00, 0x00, 0x00, 0x07, 0x8f, 0x80, 0x00, 0x00, 0x00, 
0x0f, 0x0f, 0x00, 0x00, 0x00, 0x00, 0x1e, 0x1f, 0x00, 0x00, 0x00, 0x00, 0x3c, 0x3e, 0x00, 0x00, 
0x00, 0x00, 0xf8, 0x3e, 0x00, 0x00, 0x00, 0x01, 0xe0, 0x3e, 0x00, 0x00, 0x00, 0x07, 0xc0, 0x7e, 
0x00, 0x00, 0x00, 0x1f, 0x00, 0x7f, 0x00, 0x00, 0x00, 0x7e, 0x00, 0x7f, 0xe0, 0x00, 0x07, 0xf8, 
0x00, 0x3f, 0xff, 0xff, 0xff, 0xe0, 0x00, 0x3f, 0xff, 0xff, 0xff, 0x80, 0x00, 0x1f, 0xff, 0xff, 
0xfc, 0x00, 0x00, 0x03, 0xff, 0xff, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
0x00, 0x00, 0x00`

And this is the code I get

**Comment by javl** [comment]
Is the image at the top the image you've used as input? When I convert your code into an image I get the exact same result:
![cloud](https://cloud.githubusercontent.com/assets/734644/25483327/97f99ae2-2b55-11e7-8053-bd63a7949632.png)

**Comment by mobehun** [comment]
I must have been doing something very very badly. But how come these two codes are not the same?
https://pastebin.com/rzwB6W0b
When they show the same image? (Cloud.bmp)

**Comment by javl** [comment]
Please add some more info so I know what I'm looking at; how did you get these two codes?

Also, they are not the same:
Using a 46x37 canvas I get:
First code:
![cloud1](https://cloud.githubusercontent.com/assets/734644/25488127/84dc423c-2b66-11e7-9261-386fac6ce2e8.png)
Second code:
![cloud2](https://cloud.githubusercontent.com/assets/734644/25488130/86eb9d16-2b66-11e7-9968-8505fca91d55.png)

**Comment by mobehun** [comment]
Sorry for the late reply. I think I've figured out where my error was. 
So in my code I was using the arrays as `const unsigned char cloud [] ={...}` instead of `const unsigned char PROGMEM cloud [] ={...}`
The first code is from the website while the second is made by TheDotFactory app and I've drawn it like this `ft.drawBitmap(0, 0,  cloud, 47, 32, 0xFFFF);`

**Comment by javl** [comment]
So now your images are working? Great. Still leaves us with the small-image problem, but happy your problem has been solved ;)

**Comment by javl** [comment]
Issue was caused by the last hex value not being a full 8 bits. Solved by padding it to a length of 8. See commit e6e371ad9bf5e102cf4a19adb75b3b2ed88ef227.
