### ISSUE TITLE
Bitmap Incorrect

### ISSUE THREAD

**Issue by WestonShakespear** [javl/image2cpp#11]
So when I grab a png file off of goggle and throw it in I get a perfect bitmap out of it. But if I go and edit an image in GIMP. Then I export as a png everything works including the preview until I take the bitmap code and run it on my arduino it doesn't work. All the lines seems to be scewed to the top right corner.

**Comment by javl** [comment]
I can't do much without more info. Please add the images you are using and an image of the result.

**Comment by WestonShakespear** [comment]
Okay so here is the image that I downloaded from google and input directly into your tool:
![image](https://cloud.githubusercontent.com/assets/6774408/25955499/b113cb8e-3626-11e7-9c95-cf4015eb57cb.png)
Using your tool I resized it to fit the 240x320px screen I am displaying it on, I t the bitmaps of this one four times at different thresholds so I could create the different colors, here is is on the arduino screen:
![imag0540](https://cloud.githubusercontent.com/assets/6774408/25955976/d6b5a1ae-3627-11e7-99e9-48e1fb79d596.jpg)
This one worked amazing and I was very pleased with the result, thank you. But when I tried a smaller image I made in gimp and then exported as a png:
![archer](https://cloud.githubusercontent.com/assets/6774408/25956052/fe61aefa-3627-11e7-9356-8032e95866e4.png)
I also scaled this one down to 30x30 and it displayed on the arduino like this:
![imag0541](https://cloud.githubusercontent.com/assets/6774408/25956094/13851ed4-3628-11e7-9f02-9d3fefa6ebc7.jpg)
If there is anything else you need me to supply just let me know.

**Comment by javl** [comment]
Your image is 20x20 pixels, not 30x30. Maybe you entered the wrong size somewhere?

**Comment by WestonShakespear** [comment]
My bad the picture displayed on the board is actually this one:
![untitled](https://cloud.githubusercontent.com/assets/6774408/25959248/54a3e500-3630-11e7-91f4-18d9aaac94d2.png)

**Comment by WestonShakespear** [comment]
So here is my code I use to call the bitmap:
`  tft.begin();
  tft.setRotation(2);
      tft.fillScreen(ILI9341_BLACK);
  yield();
  tft.drawBitmap(0, 0, test, 30, 30, ILI9341_GREEN);
  yield();`
The bitmap is named test and here it is:
` // 'Untitled'
const unsigned char test [] PROGMEM = {
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x07, 0x00, 0x00, 0x00, 0x1c, 
  0x00, 0x00, 0x00, 0xf0, 0x00, 0x00, 0x03, 0xc0, 0x00, 0x00, 0x0f, 0x00, 0x06, 0x00, 0x3c, 0x00, 
  0x3c, 0x00, 0xf0, 0x00, 0xf0, 0x03, 0xc0, 0x03, 0x80, 0x0e, 0x00, 0x0e, 0x00, 0x38, 0x00, 0x38, 
  0x00, 0xe0, 0x71, 0xe0, 0x03, 0x81, 0xc7, 0x80, 0x0e, 0x0f, 0x9e, 0x00, 0x3c, 0x3e, 0xf0, 0x00, 
  0xf0, 0xff, 0xc0, 0x03, 0xe7, 0xfe, 0x00, 0x07, 0x9f, 0xf8, 0x00, 0x0f, 0xff, 0xe0, 0x00, 0x1f, 
  0x9f, 0x00, 0x00, 0x7e, 0x3c, 0x00, 0x00, 0xf0, 0xe0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
  0x0
};`

I tried exporting it as vertical but it looks even more messed up kind of like the example picture. 
My settings are as follows:
Canvas Size: 30x30
Background Color: Black
Invert Background Colors: False
Brightness Threshold: 128
Scaling: Original Size
The preview looks correct
Code output format: Arduino Code
Identifier: test
Draw Mode: Horizontal

**Comment by javl** [comment]
Loading your image back into the converter shows the same image, so I don't think anything is wrong with the conversion.
When I have time I'll see if I can find a oled to test with.

**Comment by WestonShakespear** [comment]
I ran some other pictures through and it looks like when I try to convert anything under 100x100 it spits out garbage. I have tried this on multiple screens with your example code and other code.

**Comment by javl** [comment]
Ok, that might mean I get to reopen issue #1 ...

**Comment by javl** [comment]
Ok, let see if we can figure out what causes these problems.

* You're running a 240x320px screen, right?
* Can you try with an image of 110x30, and then an image of 30x110? (so a wide one and a tall one) to see if that makes any difference?
* Can you try with this one again at its original size of 20x20?: ![archer](https://cloud.githubusercontent.com/assets/6774408/25956052/fe61aefa-3627-11e7-9356-8032e95866e4.png)
* If you take a small image that doesn't work, and use my tool to create a larger version, does that larger version work?

**Comment by WestonShakespear** [comment]
Okay well I have just been using 200x200 px sprites with the 20x20 sprite in the corner. It takes more space but works.
