### ISSUE TITLE
problem with converting pictures

### ISSUE THREAD

**Issue by KayThy** [javl/image2cpp#19]
The image2cpp doesn't work for me I have been trying to convert envelope icon into bitmaps but I get the picture in truncated format.
please help or advise me on what I can do.
I am using 1-5 and 1-2 monochrome OLED with adafruit ssd1305 libraries

I tried both modes but still no luck. Thank you in advance
  
![img_20180621_111641](https://user-images.githubusercontent.com/36530759/41779228-721cafee-7631-11e8-927a-5ffeba7e6900.jpg)

**Comment by javl** [comment]
Judging by your image the image gets converted properly, as the image is recognisable (not weirdly distorted or anything).
Can you make sure you're using the actual image size everywhere? Both while converting and when drawing the image?

Are there supposed to be two envelopes and it's drawing two halves, or only one and it is being drawn incorrectly?

**Comment by KayThy** [comment]
Yes I am using the same size which is 16x11 px 
It should be a single image so it draws it incorrectly

**Comment by javl** [comment]
Can you post the image and the relevant part of your code? (Only the part loading and drawing the image)

**Comment by KayThy** [comment]
#include "notification_logo.h"

display.drawXBitmap(4, 54, Notifications, notification_width, notification_height, 1);

the picture below is converted envelope icon so I have created a notification header file.

![image](https://user-images.githubusercontent.com/36530759/41783791-0f17d222-763e-11e8-92b3-6a0702011dc2.png)

**Comment by javl** [comment]
You mentioned your image being 16x11 pixels but you seem to be drawing it at 16x9 pixels?

**Comment by javl** [comment]
Actually, after typing your byte array into the tool I noticed the resulting image is exactly the image show in your photo. I think you might have made some error with the inputs while converting. Can you post your image here so I can try converting it and see if I get the same odd result?

**Comment by KayThy** [comment]
I have attached the picture it is 16x11 i don't know how did it happen to
appear as 16x9 on your side but it is supposed to be 16x11

**Comment by javl** [comment]
Can you attach tour actual image file? The one you converted? I can't help if I don't have all the info.

**Comment by javl** [comment]
I mean that you define the image as being 16x9 in your code:
![selection_487](https://user-images.githubusercontent.com/734644/41848534-07b56d54-787e-11e8-8e5a-6b8890c39a76.png).
If this was already in the output of image2cpp, it means you dind't specify the canvas size correctly before converting.

Can you please attach the original image you tried to convert? Not a photo of the screen but the .jpg/.png whatever file you're using.
Also, when adding code please paste the actual code instead of a screenshot. That way I can simply copy paste it to test, instead of having to retype the bytestring from your image.

**Comment by javl** [comment]
No response for a week so I take this was a user error. Closing this issue.

**Comment by KayThy** [comment]
Hi, I actually massaged you on the 25th of June and I have been waiting for
your response I just thought to myself that maybe you are probably busy at
that time but I can still resend that massage if you haven't received it

**Comment by javl** [comment]
I don't see it on this page so I guess something went wrong. Can you post it again please?

**Comment by KayThy** [comment]
![images](https://user-images.githubusercontent.com/36530759/42158316-61af0c80-7df0-11e8-8258-2ece27c035f4.png)
 i don't know how did i made that mistake though i just corrected it but i still get the same picture.
Sorry for that screenshot here is the code below. 

#define notification_width 16
#define notification_height 11

static unsigned char Notifications[] PROGMEM  = {
    0x00, 0x00, 0x3f, 0xfc, 0x1f, 0xfa, 0x6f, 0xf6, 0x73, 0xce, 0x79, 0x9e, 0x7c, 0x7e, 0x7f, 0xfe,
    0x7f, 0xfe, 0x7f, 0xfe, 0x80, 0x01};

I'll think that you need an original picture that i got from the internet but this one i didn't resize it but the first picture that i have sent I have resized it to 16x11 px using paint

Thanks

**Comment by javl** [comment]
I really want to help you, but I can't help if you don't provide the info I ask for. 
If this is not the image you used before, how can I check if something is wrong with the output of my tool?
I can't compare the converted version of this image to your code because you used a different image. 

So please, resize this image to whatever size you need, then convert it using the tool and see if the code works. If it doesn't, post your resized image together with the output from the tool.

**Comment by KayThy** [comment]
![notifications](https://user-images.githubusercontent.com/36530759/42159383-e2969fc2-7df3-11e8-81d7-5fe08bbd05a2.jpg)

#define notification_width 16
#define notification_height 11

static unsigned char Notifications[]  PROGMEM  = {
       0x00, 0x00, 0x3f, 0xfc, 0x1f, 0xfa, 0x6f, 0xf6, 0x73, 0xce, 0x79,
       0x9e, 0x7c, 0x7e, 0x7f, 0xfe, 0x7f, 0xfe, 0x7f, 0xfe, 0x80, 0x01};

Tried it again and still get the same results. The size of the attached picture is 16x11px

**Comment by javl** [comment]
Hm, the output seems to be correct. When I enter your byte array into the tool I get the image again. 
Do you have the code for how you're drawing the image?

It might also be useful to try the Adafruit example [https://github.com/javl/image2cpp/blob/master/oled_example/oled_example.ino](you can find over here). First try the example as is (maybe only change it to match your display) and then try again with your image.
