### ISSUE TITLE
Background color issues

### ISSUE THREAD

**Issue by gfcwfzkm** [javl/image2cpp#22]
It seems like the tool completly ignores what image is set as background image.
No matter what I set, White becomes a '1' while Black becomes a '0'.

[lynx_image.zip](https://github.com/javl/image2cpp/files/2870430/lynx_image.zip)

**Comment by javl** [comment]
Please be clearer in what is going wrong. What do you mean with 'background image'?

**Comment by javl** [comment]
Closed because of lack of response
