### ISSUE TITLE
missing comma in generated string

### ISSUE THREAD

**Issue by aleave** [javl/image2cpp#24]
when I generate the code the last element in each row has a comma missing, e.g. here below
comma missing after 0xfc

// 'bed', 16x9px
0x00, 0x00, 0x00, 0x34, 0x00, 0x34, 0x00, 0x04, 0x5f, 0xf4, 0x5f, 0xf4, 0x40, 0x04, 0x7f, 0xfc
0x40, 0x04

**Comment by javl** [comment]
Thanks. Haven't fixed this yet, but as a quick workaround you can select Arduino Code as output and only select the bytes from the output.

**Comment by javl** [comment]
This should be fixed and only the last comma (which is unnecessary) will get removed, instead of every comma at the end of every line.
