### ISSUE TITLE
Converted picture gets scrambled

### ISSUE THREAD

**Issue by WillemOuwerkerk** [javl/image2cpp#26]
Hallo,

I had a series of eight pictures of which one gets scrambled after conversion!
But only when center horizontally was set on, all other pictures where ok.
When i switch center horizontally off the picture does convert correctly again.
By the way the converted size was 68 x 64 pixels! 

![kip-5_canvasPlus10_plus3pixel_2bits](https://user-images.githubusercontent.com/11397265/66305053-d25a9600-e8fe-11e9-8d00-677b704279f8.jpg)

Kind regards,
Willem Ouwerkerk

**Comment by jochenderwae** [comment]
Hi Willem,

I've tried the attached picture but I don't see anything wrong.
Does the issue also appear when adding only this image? Could you take a screenshot (or two) showing your settings and the issue? Is the above the exact image you tried to convert?

Thanks,
Jochen

**Comment by javl** [comment]
Closing this issue as there hasn't been any response from the poster.
