### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by joem** [javl/image2cpp#30]
Is there any particular license for this code? I'd like to modify it (strip down some of the options, add some defaults specific to my needs) and redistribute it (host my version on my website possibly with an easy 'download' button).

In case it matters: 
My specific use case is with a video synthesizer module I'm designing that uses the arduino TVout library, and I'm hoping to eventually sell a few PCBs or assembled modules, though the modular video synthesis world is quite tiny, so sales (if any) will be probably less than 30 total. Although I'm planning on selling the product my version of image2cpp would be for, the image2cpp version would be freely available to all.

**Comment by javl** [comment]
You can use it in any way you like, though I'd appreciate it if you can link to the original repo. Good luck!

**Comment by joem** [comment]
I definitely will link to the original repo. Thanks!
