### ISSUE TITLE
Multiple image titles are broken

### ISSUE THREAD

**Issue by lanslans** [javl/image2cpp#35]
If I add multiple images, and try to title them,  and set the output  to "Arduino code", only the first array gets labeled properly. The rest are myBitmap2, myBitmap3...

**Comment by lanslans** [comment]
Oh, I realize now how that "glyph" field works.

Is it possible to set the glyph field to also set the name of the variable? would be useful for processing lots of images at once.

**Comment by javl** [comment]
I think this was solved in #36
