### ISSUE TITLE
command line version

### ISSUE THREAD

**Issue by taf2** [javl/image2cpp#40]
I wanted away to generate these via the command line so I modified some of the code in index.html to allow running via node.js with canvas... here's what I have so far still testing iterating...

https://gist.github.com/taf2/5788459858fb9226a513ac1fedaf6d63

**Comment by javl** [comment]
I like the idea of a cli tool but I do feel this is somewhat outside of the scope of what I want image2cpp to do (which is to be a simple one-page tool).

Feel free to share any future updates though!
