### ISSUE TITLE
Horizontally mirrored images

### ISSUE THREAD

**Issue by marcelstoer** [javl/image2cpp#45]
This is a wonderful piece of software, thank you Jasper!

> ..I mostly found links to a piece of Windows software. Both the flakey results and the hassle of having to boot a virtual machine...

Found here exactly because of that! (Some) (Chinese) manufacturers promote that `Image2lcd.exe` by documenting its use in their display documentation.

Back on topic...I noticed that my test device running the manufacturer's sample sketch (and their driver) produces horizontally mirrored images when using your converter.

![testos](https://user-images.githubusercontent.com/624195/116059607-4c897180-a681-11eb-8a5b-a05dcfc37175.jpg)

So, to me it would be helpful to have an option to mirror image in the converter to compensate for that.

**Comment by javl** [comment]
I've added an option to flip the output. Didn't check it extensively but it should work ;)
