### ISSUE TITLE
C/Cpp2image

### ISSUE THREAD

**Issue by Swipley** [javl/image2cpp#50]
Can you make a cpp2images?

**Comment by javl** [comment]
What function do you need that's not already there? You can paste your byte array into the top right textfield and convert it to an image, which basically is cpp2image?

![image](https://user-images.githubusercontent.com/734644/144278835-6596ee2c-bff9-462b-9bba-c64503a08002.png)

**Comment by Swipley** [comment]
Like a cpp to image

**Comment by javl** [comment]
Please explain what it is you're looking for in more detail and possibly with an example.

These one-liners are way too vague to be useful.
