### ISSUE TITLE
Code output format - Error using Arduino code mode

### ISSUE THREAD

**Issue by MickyOver** [javl/image2cpp#55]
Hello, I'm having some troubles with the generated code when I use "Arduino code mode" like "Code output format". I guess that now the first part of the code is the "plain bytes". 

I attach an example of a generated code:

[jump.txt](https://github.com/javl/image2cpp/files/11405338/jump.txt)

**Comment by javl** [comment]
Oops, I made some updates and must have broken something. 
You should be fine if you just remove the first part, up to the '''// jump''' comment.
