### ISSUE TITLE
sharing of your image2cpp project

### ISSUE THREAD

**Issue by aeonSolutions** [javl/image2cpp#64]
Hi @javl ,
great tool!
I'm sharing your project on my own "Open Hardware Electronics for Volvo P2 platform" project :
[https://github.com/aeonSolutions/AeonLabs-AI-Volvo-MKII-Open-Hardware/wiki/Instruments-Cluster](https://github.com/aeonSolutions/AeonLabs-AI-Volvo-MKII-Open-Hardware/wiki/Instruments-Cluster)

**Comment by javl** [comment]
Thanks for sharing, it's always nice to see how people use the tool!
