### ISSUE TITLE
cannot remove single files while processing multiple files

### ISSUE THREAD

**Issue by mrlowalowa** [javl/image2cpp#7]
hi,

I just found this tool. Looks promising needs to check if it's working with my images. But I noticed that I was not able to remove the first picture after I processed it without hitting refresh. There is a button called remove but it did nothing.

Maybe I was just using it wrong. I'll need my files separate, will tell if I experience something different when I process my other ~10 pictures later

cheerio and great work! 👍 :)

**Comment by javl** [comment]
I noticed some problems with the first image 'sticking' as well. As it doesn't really prevent you from using the tool it's kind of low-priority, but I'll try to fix it at some point.
(cc @wiredolphin)
