### ISSUE TITLE
Vertical conversion not working

### ISSUE THREAD

**Issue by javl** [javl/image2cpp#9]
It seems somewhere along the way, the conversion to the vertical format broke.

**Comment by sirvanak** [comment]
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
   0x00, 0x3c, 0x80, 0x07, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xf8, 0x00,
   0x00, 0x00, 0x3c, 0x80, 0x07, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xfe,
   0x03, 0x00, 0x00, 0x3c, 0x80, 0x07, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
   0xff, 0x03, 0x00, 0x00, 0x3c, 0x80, 0x07, 0x00, 0x00, 0x00, 0x00, 0x00,
   0x80, 0xcf, 0x07, 0x00, 0x00, 0x3c, 0x80, 0x07, 0x00, 0x00, 0x00, 0x00,
   0x00, 0x80, 0x83, 0x07, 0x00, 0x00, 0x3c, 0x80, 0x07, 0xf8, 0x00, 0x00,
   0x00, 0x00, 0x00, 0x81, 0x07, 0x00, 0x00, 0x3c, 0x80, 0x07, 0xfc, 0x03,
   0x1c, 0x00, 0x3e, 0x1c, 0xc0, 0x03, 0x00, 0x00, 0x3c, 0x80, 0x07, 0xff,
   0x07, 0x7f, 0x80, 0xff, 0x3f, 0xe0, 0x01, 0x00, 0x00, 0x3c, 0x80, 0x07,
   0xff, 0x8f, 0xff, 0xc1, 0xff, 0x3f, 0xf0, 0x00, 0x00, 0x00, 0x3c, 0x80,
   0x87, 0xff, 0xdf, 0xff, 0xc1, 0xc3, 0x07, 0x7c, 0x00, 0x00, 0x00, 0x3c,
   0x80, 0x87, 0x0f, 0xfe, 0xff, 0xe3, 0x81, 0x03, 0x1e, 0x00, 0x00, 0x00,
   0x3c, 0x80, 0xc7, 0x07, 0xfc, 0xe3, 0xe3, 0x81, 0x07, 0x0f, 0x00, 0x00,
   0x00, 0x3c, 0x80, 0xc7, 0x07, 0xf8, 0xc1, 0xe7, 0x81, 0x87, 0xff, 0x07,
   0x00, 0x00, 0x3c, 0x80, 0xc7, 0x03, 0xf0, 0x80, 0xe7, 0xc3, 0x87, 0xff,
   0x07, 0x00, 0x00, 0x3c, 0x80, 0xc7, 0x03, 0x70, 0x80, 0xc7, 0xe7, 0x83,
   0xff, 0x07, 0x00, 0x00, 0x3c, 0x80, 0xc7, 0x03, 0x78, 0x80, 0xc7, 0xff,
   0x03, 0x00, 0x00, 0x00, 0x00, 0x3c, 0x80, 0xc7, 0x03, 0xf8, 0xc0, 0x87,
   0xff, 0x01, 0x00, 0x00, 0x00, 0x00, 0x3c, 0x80, 0xc7, 0x07, 0xfc, 0xc1,
   0xc7, 0x7f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x3c, 0xc0, 0x87, 0x0f, 0xfe,
   0xff, 0xe3, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x78, 0xc0, 0x83, 0xff,
   0xdf, 0xff, 0xe3, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0xf8, 0xf1, 0x03,
   0xff, 0x8f, 0xff, 0xe1, 0xff, 0x07, 0x00, 0x00, 0x00, 0x00, 0xf0, 0xff,
   0x01, 0xfe, 0x0f, 0xff, 0xc0, 0xff, 0x0f, 0x00, 0x00, 0x00, 0x00, 0xe0,
   0xff, 0x00, 0xfc, 0x03, 0x7c, 0xc0, 0xff, 0x1f, 0x00, 0x00, 0x00, 0x00,
   0x80, 0x3f, 0x00, 0xf8, 0x01, 0x00, 0xe0, 0x01, 0x1e, 0x00, 0x00, 0x00,
   0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xf0, 0x00, 0x1e, 0x00, 0x00,
   0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xf0, 0x00, 0x1e, 0x00,
   0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x20, 0xf0, 0xc7, 0x0f,
   0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x60, 0xe0, 0xff,
   0x0f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x60, 0xc0,
   0xff, 0x03, 0x00, 0x00, 0x00, 0x00, 0xfc, 0xff, 0xff, 0xff, 0xff, 0xff,
   0x01, 0xff, 0x00, 0x00, 0x00, 0x00, 0x00, 0xf8, 0xff, 0xff, 0xff, 0xff,
   0xff, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
   0x00, 0x60, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
   0x00, 0x00, 0x60, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
   0x00, 0x00, 0x00, 0x60, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
   0x00, 0x00, 0x00, 0x00, 0x60, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
   0x00, 0x00, 0x00, 0x00, 0x00, 0x60, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
   0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x60, 0x00, 0x00, 0x00, 0x00, 0x00,
   0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x60, 0x00, 0x00, 0x00, 0x00,
   0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x40, 0x00, 0x00, 0x00,
   0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
   0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
   0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
   0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
   0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x40, 0x24, 0x20, 0x00,
   0x00, 0x08, 0x46, 0x02, 0x00, 0x80, 0xc0, 0x40, 0x00, 0x0c, 0x6e, 0x6a,
   0xc0, 0xa4, 0x48, 0x04, 0xaa, 0xac, 0x8c, 0xaa, 0xac, 0x00, 0x6a, 0xa4,
   0xaa, 0x20, 0xea, 0xa4, 0x64, 0x66, 0xaa, 0x46, 0x4a, 0x8a, 0x00, 0x4c,
   0xa4, 0xaa, 0x20, 0xaa, 0xa2, 0x44, 0x2a, 0xaa, 0x28, 0xaa, 0x4c, 0x00,
   0xe8, 0xa8, 0x6c, 0xc4, 0xa4, 0x42, 0xee, 0x2a, 0xcc, 0x26, 0x6c, 0xe8,
   0x00, 0x06, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
   0x06, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
   0x00, 0x00, 0x00

**Comment by JJoscience** [comment]
I also have a problem with the vertical mode.  Horizontal produces a plausible byte array for my image, but vertical mode always just fills the entire array with whatever the background color is set to.

**Comment by javl** [comment]
As far as I know none of the displays I own uses the vertical mode so it's hard to really test the outcome. I'll see if I can find one that uses it so I can finally fix this issue.

**Comment by JJoscience** [comment]
So yeah, it turns out none of my displays require vertical either.  The buffer image is just stored in a weird, different way than other images are stored/rendered.

FWIW, the vertical seems to get broken when using either of the centering options.  If I try to center, it always returns nothing but the background color.  If you don't center it, it returns a plausible array, although I too can't easily render it.

Thanks for the tool in any case!  Horizontal is very helpful.

**Comment by fmarzocca** [comment]
"Vertical" draw mode gives wrong results to me. Horizontal is OK, but my display requires vertical.
Is there any trick for this?

**Comment by javl** [comment]
I don't own any vertical displays so can't really test. Don't really have time atm to dive in to this, but could you post 
1) the orginal image you're using 
2) the byte array as returned by the tool
3) a photo of the result on your display?

**Comment by fmarzocca** [comment]
It's easy to test. Just convert a bmp into codes in vertical mode with your tool. Then copy the bytes, refresh the page and insert the bytes in the form on the right. You will see that the returned image is not the original one.

**Comment by javl** [comment]
Quick test with an 8x8 image shows an output string of 8 bytes horizontal, but vertical outputs 1032 bytes. So yeah, something is wrong ;)

When I have some time I'll take a look. Can really say when that will be though, sorry.

**Comment by fmarzocca** [comment]
Ok.
Just advise when it will happen.
Thanks

**Comment by javl** [comment]
I think by posting here you've already subscribed to this issue, so you should get a message when it's updated. I'll try and remember to tag you in it.
If time permits I'll take a look at it later this week. Feel free to create a pull request if you manage to fix it in the meantime ;)

**Comment by whoisnian** [comment]
I think it's because the `settings["screenWidth"]` and `settings["screenHeight"]` are not changed when the image is uploaded. So I have made some changes and then it work well for me now.  
You can test it in [https://whoisnian.github.io/image2cpp/](https://whoisnian.github.io/image2cpp/).  
Thanks for your useful tool!

**Comment by javl** [comment]
@whoisnian
Thanks for your help figuring this out, but I can't seem to convert the image with your version either. I load an image and convert it to a vertical bytestring, then reload the page (to clear it) and try to input the bytestring directly. This still leads to a garbled image.
Did you try these steps as well, or did you only try the result on an actual display?

**Comment by whoisnian** [comment]
I load an [image](https://share.whoisnian.com/upload/archlinuxlogo.128x32.png) and then switch draw mode to "Vertical" to get plain bytes. After that I reload the page and paste the plain bytes. Finally I get a right result through "Read as vertical".

**Comment by javl** [comment]
Odd. Could you try with this image:
![abc](https://user-images.githubusercontent.com/734644/42957576-637fc3ce-8b83-11e8-83e0-7bdbc6f90c1f.png)

The result with my version of the tool was this mess:
![canvas1](https://user-images.githubusercontent.com/734644/42957602-7aa7fee0-8b83-11e8-88ab-65408df49c57.png)
With your version, I get this:
![canvas2](https://user-images.githubusercontent.com/734644/42957611-820ccc24-8b83-11e8-840c-33eb553cf10c.png)

As you can see yours is a lot better, but there seems to be some sort of offset going on still.

**Comment by javl** [comment]
Sorry, I didn't try your image yet. With yours it does work. If I expand my canvas I see things are being drawn outside of it (too far to the right) so I guess it is always drawing 128px wide instead of the width entered below the bytestring input. So your image (which is 128px wide) will work fine, but mine (which is 100px wide) gets an offset (probably 128-100 = 28 pixels)

**Comment by whoisnian** [comment]
I try your image. And I found your image is 100 x 75. Then if I input "100" and "75" below the textarea before "Read as horizontal", it will works well. Or I will get wrong result.

**Comment by javl** [comment]
What browser are you using?
Without doing anything else on the page, what output do you get when you run ```settings["screenWidth"]``` on your browser console, then change the input size and run ```settings["screenWidth"]``` again?
I get 128 both times, so it seems the value does not update for me (current Firefox on Linux)

**Comment by whoisnian** [comment]
Chrome on Linux.  
When I only open the page [https://whoisnian.github.io/image2cpp/](https://whoisnian.github.io/image2cpp/) without doing anything else, `console.log(settings["screenWidth"])` will display 128. Then I load your image and `console.log(settings["screenWidth"])` will display 100.

**Comment by javl** [comment]
Sorry if I'm unclear. What I try to do is to open the tool, paste my bytestring in there and use the "read vertical" button to convert it into an image inside the tool. Without loading an image from my filesystem.
Selecting a file from my filesystem will indeed update ```settings['screenWidth'```, but using the input boxes underneath the bytestring doesn't.

![selection_490](https://user-images.githubusercontent.com/734644/42958878-2e342ef4-8b87-11e8-99d6-a7452c8de6fe.png)

**Comment by javl** [comment]
It's kind of an odd scenario, entering the bytestring directly, but it's a good way of testing if the tool works completely, and also it allows you to recover images from your sourcecode in case you no longer have the original image file.

**Comment by javl** [comment]
Think this should fix it:

in function ```handleTextInput(drawMode)``` we set the canvas size from the input fields:

    canvas.width = parseInt(document.getElementById("text-input-width").value);
    canvas.height = parseInt(document.getElementById("text-input-height").value);

Simply copy the same value over to the settings:

    settings["screenWidth"] = canvas.width;
    settings["screenHeight"] = canvas.height;

Care to add this to your pull request?

**Comment by whoisnian** [comment]
OK, it's my fault. I didn't notice the `settings["screenWidth"]` will be used when convert bytestring into an image. And I only concentrate on the error when get bytestring from image. I will add this to my pull request.

**Comment by javl** [comment]
Thank you for your fix. Merged the pull request and closing this issue. 
I've also added a link to your profile to the credits.

@fmarzocca:
Thanks to @whoisnian your problem should be fixed now!

**Comment by whoisnian** [comment]
Sorry for my English.  
Thank you again for your patience and useful tool!

**Comment by javl** [comment]
> Sorry for my English.

Not sure what you're sorry for; didn't have any problems understanding what you wrote.
